# Generated by Django 2.0.2 on 2018-04-30 11:46

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20180430_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeModel',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('airing_type', models.CharField(blank=True, choices=[('TV', 'tv'), ('MOVIE', 'movie')], max_length=10, null=True)),
                ('airing_start_date', models.DateField(blank=True, null=True)),
                ('airing_finish_date', models.DateField(blank=True, null=True)),
                ('genre', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ACTION', 'Action'), ('DRAMA', 'Drama')], max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
