# Generated by Django 2.0.2 on 2018-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animemodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
