# Generated by Django 2.0.2 on 2018-04-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime_database', '0002_animemodel_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='animemodel',
            name='number_of_episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animemodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='anime_covers/'),
        ),
        migrations.AlterField(
            model_name='animereview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.UserProfile'),
        ),
    ]
