# Generated by Django 2.0.2 on 2018-04-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime_database', '0003_auto_20180430_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('anime', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='anime_database.AnimeModel')),
            ],
        ),
    ]
