# Generated by Django 2.0.2 on 2018-05-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0002_auto_20180506_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranimelist',
            name='list_content',
            field=models.ManyToManyField(related_name='list_content', to='anime_list.ListElement'),
        ),
    ]
